# Generated by Django 5.1.4 on 2025-02-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('coffee', 'กาแฟ'), ('chocolate', 'ช็อคโกแลต'), ('cocoa', 'โกโก้'), ('tea', 'ชา'), ('milk', 'นม'), ('bakery', 'ขนม')], max_length=10),
        ),
    ]
