# Generated by Django 5.1.4 on 2025-01-12 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_userlogin_name_userlogin_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
