# Generated by Django 5.1.4 on 2025-01-12 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_userlogin_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='date_joined',
        ),
    ]
