# Generated by Django 5.1.4 on 2025-01-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_userlogin_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
