# Generated by Django 5.1.4 on 2025-01-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_userlogin_email_alter_userlogin_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
